// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v3.21.12
// source: internal/transport/grpc/protofiles/credentials_service.proto

package proto

import (
	reflect "reflect"
	sync "sync"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CryptoBlob struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID   string `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Blob string `protobuf:"bytes,2,opt,name=Blob,proto3" json:"Blob,omitempty"` //  string ID = 5;
}

func (x *CryptoBlob) Reset() {
	*x = CryptoBlob{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_transport_grpc_protofiles_credentials_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CryptoBlob) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CryptoBlob) ProtoMessage() {}

func (x *CryptoBlob) ProtoReflect() protoreflect.Message {
	mi := &file_internal_transport_grpc_protofiles_credentials_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CryptoBlob.ProtoReflect.Descriptor instead.
func (*CryptoBlob) Descriptor() ([]byte, []int) {
	return file_internal_transport_grpc_protofiles_credentials_service_proto_rawDescGZIP(), []int{0}
}

func (x *CryptoBlob) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *CryptoBlob) GetBlob() string {
	if x != nil {
		return x.Blob
	}
	return ""
}

type BlobAddRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Cred *CryptoBlob `protobuf:"bytes,1,opt,name=cred,proto3" json:"cred,omitempty"`
}

func (x *BlobAddRequest) Reset() {
	*x = BlobAddRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_transport_grpc_protofiles_credentials_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BlobAddRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlobAddRequest) ProtoMessage() {}

func (x *BlobAddRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_transport_grpc_protofiles_credentials_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlobAddRequest.ProtoReflect.Descriptor instead.
func (*BlobAddRequest) Descriptor() ([]byte, []int) {
	return file_internal_transport_grpc_protofiles_credentials_service_proto_rawDescGZIP(), []int{1}
}

func (x *BlobAddRequest) GetCred() *CryptoBlob {
	if x != nil {
		return x.Cred
	}
	return nil
}

type BlobGetRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CredID string `protobuf:"bytes,1,opt,name=credID,proto3" json:"credID,omitempty"`
}

func (x *BlobGetRequest) Reset() {
	*x = BlobGetRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_transport_grpc_protofiles_credentials_service_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BlobGetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlobGetRequest) ProtoMessage() {}

func (x *BlobGetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_transport_grpc_protofiles_credentials_service_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlobGetRequest.ProtoReflect.Descriptor instead.
func (*BlobGetRequest) Descriptor() ([]byte, []int) {
	return file_internal_transport_grpc_protofiles_credentials_service_proto_rawDescGZIP(), []int{2}
}

func (x *BlobGetRequest) GetCredID() string {
	if x != nil {
		return x.CredID
	}
	return ""
}

type BlobGetResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Cred *CryptoBlob `protobuf:"bytes,1,opt,name=cred,proto3" json:"cred,omitempty"`
}

func (x *BlobGetResponse) Reset() {
	*x = BlobGetResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_transport_grpc_protofiles_credentials_service_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BlobGetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlobGetResponse) ProtoMessage() {}

func (x *BlobGetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_transport_grpc_protofiles_credentials_service_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlobGetResponse.ProtoReflect.Descriptor instead.
func (*BlobGetResponse) Descriptor() ([]byte, []int) {
	return file_internal_transport_grpc_protofiles_credentials_service_proto_rawDescGZIP(), []int{3}
}

func (x *BlobGetResponse) GetCred() *CryptoBlob {
	if x != nil {
		return x.Cred
	}
	return nil
}

type BlobUpdRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Blob *CryptoBlob `protobuf:"bytes,1,opt,name=blob,proto3" json:"blob,omitempty"`
}

func (x *BlobUpdRequest) Reset() {
	*x = BlobUpdRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_transport_grpc_protofiles_credentials_service_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BlobUpdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlobUpdRequest) ProtoMessage() {}

func (x *BlobUpdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_transport_grpc_protofiles_credentials_service_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlobUpdRequest.ProtoReflect.Descriptor instead.
func (*BlobUpdRequest) Descriptor() ([]byte, []int) {
	return file_internal_transport_grpc_protofiles_credentials_service_proto_rawDescGZIP(), []int{4}
}

func (x *BlobUpdRequest) GetBlob() *CryptoBlob {
	if x != nil {
		return x.Blob
	}
	return nil
}

type BlobDelRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CredID string `protobuf:"bytes,1,opt,name=credID,proto3" json:"credID,omitempty"`
}

func (x *BlobDelRequest) Reset() {
	*x = BlobDelRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_transport_grpc_protofiles_credentials_service_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BlobDelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlobDelRequest) ProtoMessage() {}

func (x *BlobDelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_transport_grpc_protofiles_credentials_service_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlobDelRequest.ProtoReflect.Descriptor instead.
func (*BlobDelRequest) Descriptor() ([]byte, []int) {
	return file_internal_transport_grpc_protofiles_credentials_service_proto_rawDescGZIP(), []int{5}
}

func (x *BlobDelRequest) GetCredID() string {
	if x != nil {
		return x.CredID
	}
	return ""
}

type BlobListResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Blobs []*CryptoBlob `protobuf:"bytes,1,rep,name=blobs,proto3" json:"blobs,omitempty"`
}

func (x *BlobListResponse) Reset() {
	*x = BlobListResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_transport_grpc_protofiles_credentials_service_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BlobListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlobListResponse) ProtoMessage() {}

func (x *BlobListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_transport_grpc_protofiles_credentials_service_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlobListResponse.ProtoReflect.Descriptor instead.
func (*BlobListResponse) Descriptor() ([]byte, []int) {
	return file_internal_transport_grpc_protofiles_credentials_service_proto_rawDescGZIP(), []int{6}
}

func (x *BlobListResponse) GetBlobs() []*CryptoBlob {
	if x != nil {
		return x.Blobs
	}
	return nil
}

var File_internal_transport_grpc_protofiles_credentials_service_proto protoreflect.FileDescriptor

var file_internal_transport_grpc_protofiles_credentials_service_proto_rawDesc = []byte{
	0x0a, 0x3c, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x74, 0x72, 0x61, 0x6e, 0x73,
	0x70, 0x6f, 0x72, 0x74, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x66,
	0x69, 0x6c, 0x65, 0x73, 0x2f, 0x63, 0x72, 0x65, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x61, 0x6c, 0x73,
	0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1b,
	0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f,
	0x65, 0x6d, 0x70, 0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x30, 0x0a, 0x0a, 0x43,
	0x72, 0x79, 0x70, 0x74, 0x6f, 0x42, 0x6c, 0x6f, 0x62, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x49, 0x44, 0x12, 0x12, 0x0a, 0x04, 0x42, 0x6c, 0x6f,
	0x62, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x42, 0x6c, 0x6f, 0x62, 0x22, 0x31, 0x0a,
	0x0e, 0x42, 0x6c, 0x6f, 0x62, 0x41, 0x64, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x1f, 0x0a, 0x04, 0x63, 0x72, 0x65, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e,
	0x43, 0x72, 0x79, 0x70, 0x74, 0x6f, 0x42, 0x6c, 0x6f, 0x62, 0x52, 0x04, 0x63, 0x72, 0x65, 0x64,
	0x22, 0x28, 0x0a, 0x0e, 0x42, 0x6c, 0x6f, 0x62, 0x47, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x63, 0x72, 0x65, 0x64, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x63, 0x72, 0x65, 0x64, 0x49, 0x44, 0x22, 0x32, 0x0a, 0x0f, 0x42, 0x6c,
	0x6f, 0x62, 0x47, 0x65, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1f, 0x0a,
	0x04, 0x63, 0x72, 0x65, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x43, 0x72,
	0x79, 0x70, 0x74, 0x6f, 0x42, 0x6c, 0x6f, 0x62, 0x52, 0x04, 0x63, 0x72, 0x65, 0x64, 0x22, 0x31,
	0x0a, 0x0e, 0x42, 0x6c, 0x6f, 0x62, 0x55, 0x70, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x1f, 0x0a, 0x04, 0x62, 0x6c, 0x6f, 0x62, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b,
	0x2e, 0x43, 0x72, 0x79, 0x70, 0x74, 0x6f, 0x42, 0x6c, 0x6f, 0x62, 0x52, 0x04, 0x62, 0x6c, 0x6f,
	0x62, 0x22, 0x28, 0x0a, 0x0e, 0x42, 0x6c, 0x6f, 0x62, 0x44, 0x65, 0x6c, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x63, 0x72, 0x65, 0x64, 0x49, 0x44, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x63, 0x72, 0x65, 0x64, 0x49, 0x44, 0x22, 0x35, 0x0a, 0x10, 0x42,
	0x6c, 0x6f, 0x62, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x21, 0x0a, 0x05, 0x62, 0x6c, 0x6f, 0x62, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0b,
	0x2e, 0x43, 0x72, 0x79, 0x70, 0x74, 0x6f, 0x42, 0x6c, 0x6f, 0x62, 0x52, 0x05, 0x62, 0x6c, 0x6f,
	0x62, 0x73, 0x32, 0x8a, 0x02, 0x0a, 0x07, 0x42, 0x6c, 0x6f, 0x62, 0x53, 0x76, 0x63, 0x12, 0x32,
	0x0a, 0x07, 0x42, 0x6c, 0x6f, 0x62, 0x41, 0x64, 0x64, 0x12, 0x0f, 0x2e, 0x42, 0x6c, 0x6f, 0x62,
	0x41, 0x64, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f,
	0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70,
	0x74, 0x79, 0x12, 0x2c, 0x0a, 0x07, 0x42, 0x6c, 0x6f, 0x62, 0x47, 0x65, 0x74, 0x12, 0x0f, 0x2e,
	0x42, 0x6c, 0x6f, 0x62, 0x47, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x10,
	0x2e, 0x42, 0x6c, 0x6f, 0x62, 0x47, 0x65, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x32, 0x0a, 0x07, 0x42, 0x6c, 0x6f, 0x62, 0x55, 0x70, 0x64, 0x12, 0x0f, 0x2e, 0x42, 0x6c,
	0x6f, 0x62, 0x55, 0x70, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x67,
	0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45,
	0x6d, 0x70, 0x74, 0x79, 0x12, 0x32, 0x0a, 0x07, 0x42, 0x6c, 0x6f, 0x62, 0x44, 0x65, 0x6c, 0x12,
	0x0f, 0x2e, 0x42, 0x6c, 0x6f, 0x62, 0x44, 0x65, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x12, 0x35, 0x0a, 0x08, 0x42, 0x6c, 0x6f, 0x62,
	0x4c, 0x69, 0x73, 0x74, 0x12, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x11, 0x2e, 0x42,
	0x6c, 0x6f, 0x62, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42,
	0x47, 0x5a, 0x45, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x77, 0x31,
	0x6e, 0x73, 0x33, 0x63, 0x2f, 0x70, 0x61, 0x73, 0x73, 0x6b, 0x65, 0x65, 0x70, 0x65, 0x72, 0x2f,
	0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x70, 0x6f,
	0x72, 0x74, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x66, 0x69, 0x6c,
	0x65, 0x73, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_internal_transport_grpc_protofiles_credentials_service_proto_rawDescOnce sync.Once
	file_internal_transport_grpc_protofiles_credentials_service_proto_rawDescData = file_internal_transport_grpc_protofiles_credentials_service_proto_rawDesc
)

func file_internal_transport_grpc_protofiles_credentials_service_proto_rawDescGZIP() []byte {
	file_internal_transport_grpc_protofiles_credentials_service_proto_rawDescOnce.Do(func() {
		file_internal_transport_grpc_protofiles_credentials_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_internal_transport_grpc_protofiles_credentials_service_proto_rawDescData)
	})
	return file_internal_transport_grpc_protofiles_credentials_service_proto_rawDescData
}

var file_internal_transport_grpc_protofiles_credentials_service_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_internal_transport_grpc_protofiles_credentials_service_proto_goTypes = []any{
	(*CryptoBlob)(nil),       // 0: CryptoBlob
	(*BlobAddRequest)(nil),   // 1: BlobAddRequest
	(*BlobGetRequest)(nil),   // 2: BlobGetRequest
	(*BlobGetResponse)(nil),  // 3: BlobGetResponse
	(*BlobUpdRequest)(nil),   // 4: BlobUpdRequest
	(*BlobDelRequest)(nil),   // 5: BlobDelRequest
	(*BlobListResponse)(nil), // 6: BlobListResponse
	(*emptypb.Empty)(nil),    // 7: google.protobuf.Empty
}
var file_internal_transport_grpc_protofiles_credentials_service_proto_depIdxs = []int32{
	0, // 0: BlobAddRequest.cred:type_name -> CryptoBlob
	0, // 1: BlobGetResponse.cred:type_name -> CryptoBlob
	0, // 2: BlobUpdRequest.blob:type_name -> CryptoBlob
	0, // 3: BlobListResponse.blobs:type_name -> CryptoBlob
	1, // 4: BlobSvc.BlobAdd:input_type -> BlobAddRequest
	2, // 5: BlobSvc.BlobGet:input_type -> BlobGetRequest
	4, // 6: BlobSvc.BlobUpd:input_type -> BlobUpdRequest
	5, // 7: BlobSvc.BlobDel:input_type -> BlobDelRequest
	7, // 8: BlobSvc.BlobList:input_type -> google.protobuf.Empty
	7, // 9: BlobSvc.BlobAdd:output_type -> google.protobuf.Empty
	3, // 10: BlobSvc.BlobGet:output_type -> BlobGetResponse
	7, // 11: BlobSvc.BlobUpd:output_type -> google.protobuf.Empty
	7, // 12: BlobSvc.BlobDel:output_type -> google.protobuf.Empty
	6, // 13: BlobSvc.BlobList:output_type -> BlobListResponse
	9, // [9:14] is the sub-list for method output_type
	4, // [4:9] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_internal_transport_grpc_protofiles_credentials_service_proto_init() }
func file_internal_transport_grpc_protofiles_credentials_service_proto_init() {
	if File_internal_transport_grpc_protofiles_credentials_service_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_internal_transport_grpc_protofiles_credentials_service_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*CryptoBlob); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_transport_grpc_protofiles_credentials_service_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*BlobAddRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_transport_grpc_protofiles_credentials_service_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*BlobGetRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_transport_grpc_protofiles_credentials_service_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*BlobGetResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_transport_grpc_protofiles_credentials_service_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*BlobUpdRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_transport_grpc_protofiles_credentials_service_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*BlobDelRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_transport_grpc_protofiles_credentials_service_proto_msgTypes[6].Exporter = func(v any, i int) any {
			switch v := v.(*BlobListResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_internal_transport_grpc_protofiles_credentials_service_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_transport_grpc_protofiles_credentials_service_proto_goTypes,
		DependencyIndexes: file_internal_transport_grpc_protofiles_credentials_service_proto_depIdxs,
		MessageInfos:      file_internal_transport_grpc_protofiles_credentials_service_proto_msgTypes,
	}.Build()
	File_internal_transport_grpc_protofiles_credentials_service_proto = out.File
	file_internal_transport_grpc_protofiles_credentials_service_proto_rawDesc = nil
	file_internal_transport_grpc_protofiles_credentials_service_proto_goTypes = nil
	file_internal_transport_grpc_protofiles_credentials_service_proto_depIdxs = nil
}
