// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.12.4
// source: credentials_service.proto

package protofiles

import (
	empty "github.com/golang/protobuf/ptypes/empty"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Credential struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Login       string `protobuf:"bytes,1,opt,name=Login,proto3" json:"Login,omitempty"`
	Password    string `protobuf:"bytes,2,opt,name=Password,proto3" json:"Password,omitempty"`
	Resource    string `protobuf:"bytes,3,opt,name=Resource,proto3" json:"Resource,omitempty"`
	Description string `protobuf:"bytes,4,opt,name=Description,proto3" json:"Description,omitempty"`
	Date        string `protobuf:"bytes,5,opt,name=Date,proto3" json:"Date,omitempty"` //  string ID = 5;
}

func (x *Credential) Reset() {
	*x = Credential{}
	if protoimpl.UnsafeEnabled {
		mi := &file_credentials_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Credential) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Credential) ProtoMessage() {}

func (x *Credential) ProtoReflect() protoreflect.Message {
	mi := &file_credentials_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Credential.ProtoReflect.Descriptor instead.
func (*Credential) Descriptor() ([]byte, []int) {
	return file_credentials_service_proto_rawDescGZIP(), []int{0}
}

func (x *Credential) GetLogin() string {
	if x != nil {
		return x.Login
	}
	return ""
}

func (x *Credential) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *Credential) GetResource() string {
	if x != nil {
		return x.Resource
	}
	return ""
}

func (x *Credential) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Credential) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

type CredAddRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Cred *Credential `protobuf:"bytes,1,opt,name=cred,proto3" json:"cred,omitempty"`
}

func (x *CredAddRequest) Reset() {
	*x = CredAddRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_credentials_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CredAddRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CredAddRequest) ProtoMessage() {}

func (x *CredAddRequest) ProtoReflect() protoreflect.Message {
	mi := &file_credentials_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CredAddRequest.ProtoReflect.Descriptor instead.
func (*CredAddRequest) Descriptor() ([]byte, []int) {
	return file_credentials_service_proto_rawDescGZIP(), []int{1}
}

func (x *CredAddRequest) GetCred() *Credential {
	if x != nil {
		return x.Cred
	}
	return nil
}

type CredGetRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CredID string `protobuf:"bytes,1,opt,name=credID,proto3" json:"credID,omitempty"`
}

func (x *CredGetRequest) Reset() {
	*x = CredGetRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_credentials_service_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CredGetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CredGetRequest) ProtoMessage() {}

func (x *CredGetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_credentials_service_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CredGetRequest.ProtoReflect.Descriptor instead.
func (*CredGetRequest) Descriptor() ([]byte, []int) {
	return file_credentials_service_proto_rawDescGZIP(), []int{2}
}

func (x *CredGetRequest) GetCredID() string {
	if x != nil {
		return x.CredID
	}
	return ""
}

type CredGetResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Cred *Credential `protobuf:"bytes,1,opt,name=cred,proto3" json:"cred,omitempty"`
}

func (x *CredGetResponse) Reset() {
	*x = CredGetResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_credentials_service_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CredGetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CredGetResponse) ProtoMessage() {}

func (x *CredGetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_credentials_service_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CredGetResponse.ProtoReflect.Descriptor instead.
func (*CredGetResponse) Descriptor() ([]byte, []int) {
	return file_credentials_service_proto_rawDescGZIP(), []int{3}
}

func (x *CredGetResponse) GetCred() *Credential {
	if x != nil {
		return x.Cred
	}
	return nil
}

type CredUpdRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CredID string      `protobuf:"bytes,1,opt,name=credID,proto3" json:"credID,omitempty"`
	Cred   *Credential `protobuf:"bytes,2,opt,name=cred,proto3" json:"cred,omitempty"`
}

func (x *CredUpdRequest) Reset() {
	*x = CredUpdRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_credentials_service_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CredUpdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CredUpdRequest) ProtoMessage() {}

func (x *CredUpdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_credentials_service_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CredUpdRequest.ProtoReflect.Descriptor instead.
func (*CredUpdRequest) Descriptor() ([]byte, []int) {
	return file_credentials_service_proto_rawDescGZIP(), []int{4}
}

func (x *CredUpdRequest) GetCredID() string {
	if x != nil {
		return x.CredID
	}
	return ""
}

func (x *CredUpdRequest) GetCred() *Credential {
	if x != nil {
		return x.Cred
	}
	return nil
}

type CredDelRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CredID string `protobuf:"bytes,1,opt,name=credID,proto3" json:"credID,omitempty"`
}

func (x *CredDelRequest) Reset() {
	*x = CredDelRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_credentials_service_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CredDelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CredDelRequest) ProtoMessage() {}

func (x *CredDelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_credentials_service_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CredDelRequest.ProtoReflect.Descriptor instead.
func (*CredDelRequest) Descriptor() ([]byte, []int) {
	return file_credentials_service_proto_rawDescGZIP(), []int{5}
}

func (x *CredDelRequest) GetCredID() string {
	if x != nil {
		return x.CredID
	}
	return ""
}

type CredListResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Creds []*Credential `protobuf:"bytes,1,rep,name=creds,proto3" json:"creds,omitempty"`
}

func (x *CredListResponse) Reset() {
	*x = CredListResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_credentials_service_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CredListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CredListResponse) ProtoMessage() {}

func (x *CredListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_credentials_service_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CredListResponse.ProtoReflect.Descriptor instead.
func (*CredListResponse) Descriptor() ([]byte, []int) {
	return file_credentials_service_proto_rawDescGZIP(), []int{6}
}

func (x *CredListResponse) GetCreds() []*Credential {
	if x != nil {
		return x.Creds
	}
	return nil
}

var File_credentials_service_proto protoreflect.FileDescriptor

var file_credentials_service_proto_rawDesc = []byte{
	0x0a, 0x19, 0x63, 0x72, 0x65, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x61, 0x6c, 0x73, 0x5f, 0x73, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1b, 0x67, 0x6f, 0x6f,
	0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x65, 0x6d, 0x70,
	0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x90, 0x01, 0x0a, 0x0a, 0x43, 0x72, 0x65,
	0x64, 0x65, 0x6e, 0x74, 0x69, 0x61, 0x6c, 0x12, 0x14, 0x0a, 0x05, 0x4c, 0x6f, 0x67, 0x69, 0x6e,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x12, 0x1a, 0x0a,
	0x08, 0x50, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x50, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x52, 0x65, 0x73,
	0x6f, 0x75, 0x72, 0x63, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x52, 0x65, 0x73,
	0x6f, 0x75, 0x72, 0x63, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70,
	0x74, 0x69, 0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x44, 0x65, 0x73, 0x63,
	0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x44, 0x61, 0x74, 0x65, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x44, 0x61, 0x74, 0x65, 0x22, 0x31, 0x0a, 0x0e, 0x43,
	0x72, 0x65, 0x64, 0x41, 0x64, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1f, 0x0a,
	0x04, 0x63, 0x72, 0x65, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x43, 0x72,
	0x65, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x61, 0x6c, 0x52, 0x04, 0x63, 0x72, 0x65, 0x64, 0x22, 0x28,
	0x0a, 0x0e, 0x43, 0x72, 0x65, 0x64, 0x47, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x16, 0x0a, 0x06, 0x63, 0x72, 0x65, 0x64, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x63, 0x72, 0x65, 0x64, 0x49, 0x44, 0x22, 0x32, 0x0a, 0x0f, 0x43, 0x72, 0x65, 0x64,
	0x47, 0x65, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1f, 0x0a, 0x04, 0x63,
	0x72, 0x65, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x43, 0x72, 0x65, 0x64,
	0x65, 0x6e, 0x74, 0x69, 0x61, 0x6c, 0x52, 0x04, 0x63, 0x72, 0x65, 0x64, 0x22, 0x49, 0x0a, 0x0e,
	0x43, 0x72, 0x65, 0x64, 0x55, 0x70, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16,
	0x0a, 0x06, 0x63, 0x72, 0x65, 0x64, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x63, 0x72, 0x65, 0x64, 0x49, 0x44, 0x12, 0x1f, 0x0a, 0x04, 0x63, 0x72, 0x65, 0x64, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x43, 0x72, 0x65, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x61,
	0x6c, 0x52, 0x04, 0x63, 0x72, 0x65, 0x64, 0x22, 0x28, 0x0a, 0x0e, 0x43, 0x72, 0x65, 0x64, 0x44,
	0x65, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x63, 0x72, 0x65,
	0x64, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x63, 0x72, 0x65, 0x64, 0x49,
	0x44, 0x22, 0x35, 0x0a, 0x10, 0x43, 0x72, 0x65, 0x64, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x21, 0x0a, 0x05, 0x63, 0x72, 0x65, 0x64, 0x73, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x43, 0x72, 0x65, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x61,
	0x6c, 0x52, 0x05, 0x63, 0x72, 0x65, 0x64, 0x73, 0x32, 0x8a, 0x02, 0x0a, 0x07, 0x43, 0x72, 0x65,
	0x64, 0x53, 0x76, 0x63, 0x12, 0x32, 0x0a, 0x07, 0x43, 0x72, 0x65, 0x64, 0x41, 0x64, 0x64, 0x12,
	0x0f, 0x2e, 0x43, 0x72, 0x65, 0x64, 0x41, 0x64, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x12, 0x2c, 0x0a, 0x07, 0x43, 0x72, 0x65, 0x64,
	0x47, 0x65, 0x74, 0x12, 0x0f, 0x2e, 0x43, 0x72, 0x65, 0x64, 0x47, 0x65, 0x74, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x10, 0x2e, 0x43, 0x72, 0x65, 0x64, 0x47, 0x65, 0x74, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x32, 0x0a, 0x07, 0x43, 0x72, 0x65, 0x64, 0x55, 0x70,
	0x64, 0x12, 0x0f, 0x2e, 0x43, 0x72, 0x65, 0x64, 0x55, 0x70, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x12, 0x32, 0x0a, 0x07, 0x43, 0x72,
	0x65, 0x64, 0x44, 0x65, 0x6c, 0x12, 0x0f, 0x2e, 0x43, 0x72, 0x65, 0x64, 0x44, 0x65, 0x6c, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x12, 0x35,
	0x0a, 0x08, 0x43, 0x72, 0x65, 0x64, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x16, 0x2e, 0x67, 0x6f, 0x6f,
	0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70,
	0x74, 0x79, 0x1a, 0x11, 0x2e, 0x43, 0x72, 0x65, 0x64, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x41, 0x5a, 0x3f, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e,
	0x63, 0x6f, 0x6d, 0x2f, 0x77, 0x31, 0x6e, 0x73, 0x33, 0x63, 0x2f, 0x70, 0x61, 0x73, 0x73, 0x6b,
	0x65, 0x65, 0x70, 0x65, 0x72, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x74,
	0x72, 0x61, 0x6e, 0x73, 0x70, 0x6f, 0x72, 0x74, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_credentials_service_proto_rawDescOnce sync.Once
	file_credentials_service_proto_rawDescData = file_credentials_service_proto_rawDesc
)

func file_credentials_service_proto_rawDescGZIP() []byte {
	file_credentials_service_proto_rawDescOnce.Do(func() {
		file_credentials_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_credentials_service_proto_rawDescData)
	})
	return file_credentials_service_proto_rawDescData
}

var file_credentials_service_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_credentials_service_proto_goTypes = []interface{}{
	(*Credential)(nil),       // 0: Credential
	(*CredAddRequest)(nil),   // 1: CredAddRequest
	(*CredGetRequest)(nil),   // 2: CredGetRequest
	(*CredGetResponse)(nil),  // 3: CredGetResponse
	(*CredUpdRequest)(nil),   // 4: CredUpdRequest
	(*CredDelRequest)(nil),   // 5: CredDelRequest
	(*CredListResponse)(nil), // 6: CredListResponse
	(*empty.Empty)(nil),      // 7: google.protobuf.Empty
}
var file_credentials_service_proto_depIdxs = []int32{
	0, // 0: CredAddRequest.cred:type_name -> Credential
	0, // 1: CredGetResponse.cred:type_name -> Credential
	0, // 2: CredUpdRequest.cred:type_name -> Credential
	0, // 3: CredListResponse.creds:type_name -> Credential
	1, // 4: CredSvc.CredAdd:input_type -> CredAddRequest
	2, // 5: CredSvc.CredGet:input_type -> CredGetRequest
	4, // 6: CredSvc.CredUpd:input_type -> CredUpdRequest
	5, // 7: CredSvc.CredDel:input_type -> CredDelRequest
	7, // 8: CredSvc.CredList:input_type -> google.protobuf.Empty
	7, // 9: CredSvc.CredAdd:output_type -> google.protobuf.Empty
	3, // 10: CredSvc.CredGet:output_type -> CredGetResponse
	7, // 11: CredSvc.CredUpd:output_type -> google.protobuf.Empty
	7, // 12: CredSvc.CredDel:output_type -> google.protobuf.Empty
	6, // 13: CredSvc.CredList:output_type -> CredListResponse
	9, // [9:14] is the sub-list for method output_type
	4, // [4:9] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_credentials_service_proto_init() }
func file_credentials_service_proto_init() {
	if File_credentials_service_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_credentials_service_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Credential); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_credentials_service_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CredAddRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_credentials_service_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CredGetRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_credentials_service_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CredGetResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_credentials_service_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CredUpdRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_credentials_service_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CredDelRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_credentials_service_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CredListResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_credentials_service_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_credentials_service_proto_goTypes,
		DependencyIndexes: file_credentials_service_proto_depIdxs,
		MessageInfos:      file_credentials_service_proto_msgTypes,
	}.Build()
	File_credentials_service_proto = out.File
	file_credentials_service_proto_rawDesc = nil
	file_credentials_service_proto_goTypes = nil
	file_credentials_service_proto_depIdxs = nil
}
