// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: internal/transport/grpc/protofiles/users_change_pwd.proto

package proto

import (
	context "context"

	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	UserChangePassSvc_ChangePass_FullMethodName = "/UserChangePassSvc/ChangePass"
)

// UserChangePassSvcClient is the client API for UserChangePassSvc service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type UserChangePassSvcClient interface {
	ChangePass(ctx context.Context, in *UserChangePassReq, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type userChangePassSvcClient struct {
	cc grpc.ClientConnInterface
}

func NewUserChangePassSvcClient(cc grpc.ClientConnInterface) UserChangePassSvcClient {
	return &userChangePassSvcClient{cc}
}

func (c *userChangePassSvcClient) ChangePass(ctx context.Context, in *UserChangePassReq, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, UserChangePassSvc_ChangePass_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserChangePassSvcServer is the server API for UserChangePassSvc service.
// All implementations must embed UnimplementedUserChangePassSvcServer
// for forward compatibility.
type UserChangePassSvcServer interface {
	ChangePass(context.Context, *UserChangePassReq) (*emptypb.Empty, error)
	mustEmbedUnimplementedUserChangePassSvcServer()
}

// UnimplementedUserChangePassSvcServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedUserChangePassSvcServer struct{}

func (UnimplementedUserChangePassSvcServer) ChangePass(context.Context, *UserChangePassReq) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ChangePass not implemented")
}
func (UnimplementedUserChangePassSvcServer) mustEmbedUnimplementedUserChangePassSvcServer() {}
func (UnimplementedUserChangePassSvcServer) testEmbeddedByValue()                           {}

// UnsafeUserChangePassSvcServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UserChangePassSvcServer will
// result in compilation errors.
type UnsafeUserChangePassSvcServer interface {
	mustEmbedUnimplementedUserChangePassSvcServer()
}

func RegisterUserChangePassSvcServer(s grpc.ServiceRegistrar, srv UserChangePassSvcServer) {
	// If the following call pancis, it indicates UnimplementedUserChangePassSvcServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&UserChangePassSvc_ServiceDesc, srv)
}

func _UserChangePassSvc_ChangePass_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserChangePassReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserChangePassSvcServer).ChangePass(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserChangePassSvc_ChangePass_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserChangePassSvcServer).ChangePass(ctx, req.(*UserChangePassReq))
	}
	return interceptor(ctx, in, info, handler)
}

// UserChangePassSvc_ServiceDesc is the grpc.ServiceDesc for UserChangePassSvc service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var UserChangePassSvc_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "UserChangePassSvc",
	HandlerType: (*UserChangePassSvcServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ChangePass",
			Handler:    _UserChangePassSvc_ChangePass_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "internal/transport/grpc/protofiles/users_change_pwd.proto",
}
