// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.12.4
// source: users_change_pwd.proto

package protofiles

import (
	context "context"
	empty "github.com/golang/protobuf/ptypes/empty"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// UserPassSvcClient is the client API for UserPassSvc service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type UserPassSvcClient interface {
	ChangePass(ctx context.Context, in *UserChangePassReq, opts ...grpc.CallOption) (*empty.Empty, error)
}

type userPassSvcClient struct {
	cc grpc.ClientConnInterface
}

func NewUserPassSvcClient(cc grpc.ClientConnInterface) UserPassSvcClient {
	return &userPassSvcClient{cc}
}

func (c *userPassSvcClient) ChangePass(ctx context.Context, in *UserChangePassReq, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/UserPassSvc/ChangePass", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserPassSvcServer is the server API for UserPassSvc service.
// All implementations must embed UnimplementedUserPassSvcServer
// for forward compatibility
type UserPassSvcServer interface {
	ChangePass(context.Context, *UserChangePassReq) (*empty.Empty, error)
	mustEmbedUnimplementedUserPassSvcServer()
}

// UnimplementedUserPassSvcServer must be embedded to have forward compatible implementations.
type UnimplementedUserPassSvcServer struct {
}

func (UnimplementedUserPassSvcServer) ChangePass(context.Context, *UserChangePassReq) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ChangePass not implemented")
}
func (UnimplementedUserPassSvcServer) mustEmbedUnimplementedUserPassSvcServer() {}

// UnsafeUserPassSvcServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UserPassSvcServer will
// result in compilation errors.
type UnsafeUserPassSvcServer interface {
	mustEmbedUnimplementedUserPassSvcServer()
}

func RegisterUserPassSvcServer(s grpc.ServiceRegistrar, srv UserPassSvcServer) {
	s.RegisterService(&UserPassSvc_ServiceDesc, srv)
}

func _UserPassSvc_ChangePass_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserChangePassReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserPassSvcServer).ChangePass(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/UserPassSvc/ChangePass",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserPassSvcServer).ChangePass(ctx, req.(*UserChangePassReq))
	}
	return interceptor(ctx, in, info, handler)
}

// UserPassSvc_ServiceDesc is the grpc.ServiceDesc for UserPassSvc service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var UserPassSvc_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "UserPassSvc",
	HandlerType: (*UserPassSvcServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ChangePass",
			Handler:    _UserPassSvc_ChangePass_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "users_change_pwd.proto",
}
