// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: internal/transport/grpc/protofiles/users_change_pwd.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	UserPassSvc_ChangePass_FullMethodName = "/UserPassSvc/ChangePass"
)

// UserPassSvcClient is the client API for UserPassSvc service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type UserPassSvcClient interface {
	ChangePass(ctx context.Context, in *UserChangePassReq, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type userPassSvcClient struct {
	cc grpc.ClientConnInterface
}

func NewUserPassSvcClient(cc grpc.ClientConnInterface) UserPassSvcClient {
	return &userPassSvcClient{cc}
}

func (c *userPassSvcClient) ChangePass(ctx context.Context, in *UserChangePassReq, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, UserPassSvc_ChangePass_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserPassSvcServer is the server API for UserPassSvc service.
// All implementations must embed UnimplementedUserPassSvcServer
// for forward compatibility.
type UserPassSvcServer interface {
	ChangePass(context.Context, *UserChangePassReq) (*emptypb.Empty, error)
	mustEmbedUnimplementedUserPassSvcServer()
}

// UnimplementedUserPassSvcServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedUserPassSvcServer struct{}

func (UnimplementedUserPassSvcServer) ChangePass(context.Context, *UserChangePassReq) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ChangePass not implemented")
}
func (UnimplementedUserPassSvcServer) mustEmbedUnimplementedUserPassSvcServer() {}
func (UnimplementedUserPassSvcServer) testEmbeddedByValue()                     {}

// UnsafeUserPassSvcServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UserPassSvcServer will
// result in compilation errors.
type UnsafeUserPassSvcServer interface {
	mustEmbedUnimplementedUserPassSvcServer()
}

func RegisterUserPassSvcServer(s grpc.ServiceRegistrar, srv UserPassSvcServer) {
	// If the following call pancis, it indicates UnimplementedUserPassSvcServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&UserPassSvc_ServiceDesc, srv)
}

func _UserPassSvc_ChangePass_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserChangePassReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserPassSvcServer).ChangePass(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserPassSvc_ChangePass_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserPassSvcServer).ChangePass(ctx, req.(*UserChangePassReq))
	}
	return interceptor(ctx, in, info, handler)
}

// UserPassSvc_ServiceDesc is the grpc.ServiceDesc for UserPassSvc service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var UserPassSvc_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "UserPassSvc",
	HandlerType: (*UserPassSvcServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ChangePass",
			Handler:    _UserPassSvc_ChangePass_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "internal/transport/grpc/protofiles/users_change_pwd.proto",
}
