package entities

// Banks contains banks list for application.
var Banks = []string{
	"Absolut Bank",
	"Ak Bars",
	"Alfa-Bank",
	"B&N Bank",
	"Bank Otkritie",
	"Bank Saint-Petersburg",
	"Bank Severny Morskoy Put",
	"Bank Uralsib",
	"BM-Bank",
	"Citibank",
	"Credit & Finance Bank",
	"Credit Bank of Moscow",
	"Express-Volga",
	"Gazprombank",
	"ING Bank",
	"Joint Stock Bank Russia",
	"Jugra Bank",
	"Moscow Industrial bank",
	"Moscow Regional Bank",
	"National Bank TRUST",
	"National Clearing Centre",
	"Nordea Bank",
	"Novikombank",
	"Orient Express Bank",
	"Peresvet Bank",
	"Post Bank",
	"Promsvyazbank",
	"Raiffeisenbank",
	"Regional Development Bank",
	"Rosbank",
	"Rost Bank",
	"Russian Agricultural Bank",
	"Russian Capital",
	"Russian Standard Bank",
	"Sberbank",
	"Sovcombank",
	"Surgutneftegasbank",
	"Sviaz-Bank",
	"The Ural Bank",
	"T-Bank",
	"Transcapitalbank",
	"UniCredit Bank",
	"Vozrozhdenie Bank",
	"VTB 24",
	"VTB Bank Moscow",
	"Zenit Bank",
	"Other",
}
